// Static club → league mapping for all 97 clubs in players_clean.csv
export const CLUB_LEAGUE_MAP: Record<string, string> = {
  // Premier League
  "Arsenal": "Premier League",
  "Aston Villa": "Premier League",
  "Bournemouth": "Premier League",
  "Brentford": "Premier League",
  "Brighton & Hove Albion": "Premier League",
  "Chelsea": "Premier League",
  "Crystal Palace": "Premier League",
  "Everton": "Premier League",
  "Fulham": "Premier League",
  "Ipswich Town": "Premier League",
  "Leicester City": "Premier League",
  "Liverpool": "Premier League",
  "Manchester City": "Premier League",
  "Manchester United": "Premier League",
  "Newcastle United": "Premier League",
  "Nottingham Forest": "Premier League",
  "Southampton": "Premier League",
  "Tottenham Hotspur": "Premier League",
  "West Ham United": "Premier League",
  "Wolverhampton Wanderers": "Premier League",
  // La Liga
  "Athletic Bilbao": "La Liga",
  "Atletico Madrid": "La Liga",
  "Celta Vigo": "La Liga",
  "Deportivo Alaves": "La Liga",
  "Espanyol": "La Liga",
  "FC Barcelona": "La Liga",
  "Getafe CF": "La Liga",
  "Girona FC": "La Liga",
  "Osasuna": "La Liga",
  "Rayo Vallecano": "La Liga",
  "RCD Mallorca": "La Liga",
  "Real Betis": "La Liga",
  "Real Madrid": "La Liga",
  "Real Sociedad": "La Liga",
  "Real Valladolid": "La Liga",
  "Sevilla FC": "La Liga",
  "UD Las Palmas": "La Liga",
  "Valencia CF": "La Liga",
  "Villarreal CF": "La Liga",
  // Bundesliga
  "1. FC Heidenheim": "Bundesliga",
  "1. FC Union Berlin": "Bundesliga",
  "Bayer Leverkusen": "Bundesliga",
  "Bayern Munich": "Bundesliga",
  "Borussia Dortmund": "Bundesliga",
  "Borussia Monchengladbach": "Bundesliga",
  "Eintracht Frankfurt": "Bundesliga",
  "FC Augsburg": "Bundesliga",
  "FC St. Pauli": "Bundesliga",
  "RB Leipzig": "Bundesliga",
  "SC Freiburg": "Bundesliga",
  "SV Darmstadt 98": "Bundesliga",
  "TSG Hoffenheim": "Bundesliga",
  "VfB Stuttgart": "Bundesliga",
  "VfL Bochum": "Bundesliga",
  "VfL Wolfsburg": "Bundesliga",
  "Werder Bremen": "Bundesliga",
  // Serie A
  "AC Milan": "Serie A",
  "AS Roma": "Serie A",
  "Atalanta": "Serie A",
  "Bologna": "Serie A",
  "Cagliari": "Serie A",
  "Como": "Serie A",
  "Empoli": "Serie A",
  "Fiorentina": "Serie A",
  "Genoa": "Serie A",
  "Hellas Verona": "Serie A",
  "Inter Milan": "Serie A",
  "Juventus": "Serie A",
  "Lazio": "Serie A",
  "Lecce": "Serie A",
  "Monza": "Serie A",
  "Parma": "Serie A",
  "SSC Napoli": "Serie A",
  "Torino": "Serie A",
  "Udinese": "Serie A",
  "Venezia": "Serie A",
  // Ligue 1
  "Angers SCO": "Ligue 1",
  "AS Monaco": "Ligue 1",
  "Auxerre": "Ligue 1",
  "FC Nantes": "Ligue 1",
  "Le Havre AC": "Ligue 1",
  "Lille OSC": "Ligue 1",
  "Montpellier HSC": "Ligue 1",
  "OGC Nice": "Ligue 1",
  "Olympique Lyonnais": "Ligue 1",
  "Olympique de Marseille": "Ligue 1",
  "Paris Saint-Germain": "Ligue 1",
  "RC Lens": "Ligue 1",
  "Saint-Etienne": "Ligue 1",
  "Stade Brestois": "Ligue 1",
  "Stade Rennais": "Ligue 1",
  "Strasbourg": "Ligue 1",
  "Toulouse FC": "Ligue 1",
  // Süper Lig
  "Besiktas": "Süper Lig",
  "Fenerbahce": "Süper Lig",
  "Galatasaray": "Süper Lig",
  "Trabzonspor": "Süper Lig",
};

export function groupClubsByLeague(clubs: string[]): Record<string, string[]> {
  const grouped: Record<string, string[]> = {};
  for (const club of clubs) {
    const league = CLUB_LEAGUE_MAP[club] || "Other";
    if (!grouped[league]) grouped[league] = [];
    grouped[league].push(club);
  }
  return grouped;
}
